#!/bin/bash
echo "installing..."
if [[ "$1" == "-t" ]]
        then
        echo "termux installation"
        cp housefetch $HOME/../usr/bin/
        chmod +x $HOME/../usr/bin/housefetch
        mkdir -p $HOME/../usr/share/doc/housefetch
        cp config $HOME/../usr/share/doc/housefetch/
        chmod +x $HOME/../usr/share/doc/housefetch/config
else
        cp housefetch /bin/housefetch
        chmod +x /bin/housefetch
        mkdir -p /usr/share/doc/housefetch
        cp config /usr/share/doc/housefetch
        chmod +x /usr/share/doc/housefetch/config
fi
echo "all done! Copy config file to $HOME/.config/housefetch/config !"
echo "you can find default config in /usr/share/doc/housefetch"
echo "($HOME/../usr/share/doc/housefetch in termux)"
exit 0
